### ISSUE TITLE
klogger not found

### ISSUE THREAD

**Issue by inztinkt** [trustedlogin/trustedlogin-client#27]
debug.log contains the following: 

`ReplaceMe\TrustedLogin\Logging::setup_klogger (error): KReplaceMe_ReplaceMe_Logger not found.`

Could this be due to composer/mozart @zackkatz ?

**Comment by zackkatz** [comment]
Yes. I’ll check as well.

**Comment by zackkatz** [comment]
Fixed with Strauss
