### ISSUE TITLE
switch from modals to authpage

### ISSUE THREAD

**Issue by inztinkt** [trustedlogin/trustedlogin-client#28]
Dropping jquery.confirm from the plugin.

- [x]  Connect grant button to inline JS -> AJAX -> inline Status
- [x]  Connect extend button to inline JS -> AJAX -> inline Status
- [x]  Show the AccessKey on the auth page. 
- [ ]  Link buttons to auth page and remove any hooked JS events.

**Comment by inztinkt** [comment]
@zackkatz how should we handle buttons added via the shortcode/do_action? Redirect to auth page?

**Comment by zackkatz** [comment]
@inztinkt yep
