### ISSUE TITLE
Convert md5 to sha256

### ISSUE THREAD

**Issue by zackkatz** [trustedlogin/trustedlogin-client#3]
Let's just do this.

`hash( 'sha256' , $data );`

Edit: It may not be available in PHP 5.2…Can we use `sha256` on 5.3+ and `md5` on 5.2?

**Comment by Shelob9** [comment]
> It may not be available in PHP 5.2…Can we use sha256 on 5.3+ and md5 on 5.2?
Why does this matter, just put in a version check so that configuration validation always throws an exception on any version of PHP5.

**Comment by zackkatz** [comment]
It's to be distributed on .org…5.2 [is still at 15.8%](https://wordpress.org/about/stats/).

![](https://i.gravityview.co/z3rd9X+)

I was tempted to require 5.6, but I want broad adoption…

**Comment by Shelob9** [comment]
Counter-point: If I can crack the endpoint hash, I can pwn your site. With md5 that should take about 30 minutes per site. With sha256 that will take 10^56 minutes.

**Comment by zackkatz** [comment]
Yes, a `md5()` endpoint hash is weak. It's one part of two needed pieces: to login, [you also need the identifier](https://github.com/trustedlogin/trustedlogin-client/blob/987efd9a362a3294e921e9f64ae0f796cbc84158/src/Client.php#L328-L334), a 64-character string [generated here](https://github.com/trustedlogin/trustedlogin-client/blob/987efd9a362a3294e921e9f64ae0f796cbc84158/src/Client.php#L494-L503).

If you still think we need `sha256` for all sites, I'm totally on-board with setting a minimum of 5.3. Based on this, do you think it's okay to go md5 for PHP 5.2.x?

**Comment by Shelob9** [comment]
![Do you want ants?](https://i.kym-cdn.com/entries/icons/original/000/015/319/do_you_want_ants.jpg)

>If you still think we need sha256 for all sites,

I think this is the only viable option.

> I'm totally on-board with setting a minimum of 5.3. Based on this, do you think it's okay to go md5 for PHP 5.2.x?
No. I would recommend not loading the client on PHP 5.2. Supporting PHP 5.2 leads to these kind of "well it's less secure, but..." type explanations.

**Comment by zackkatz** [comment]
Okay, thanks for pushing for the right solution :-) 🙏

**Comment by zackkatz** [comment]
Glad to report that 5.2 no longer an issue and we no longer use md5() except as a hash cron.

![](https://i.gravityview.co/Gva6Mz+)
