### ISSUE TITLE
Let SaaS know that session was extended

### ISSUE THREAD

**Issue by inztinkt** [trustedlogin/trustedlogin-client#31]
From `TrustedLogin\Client->extend_access()`

Data we have: 

```
$return_data = array(
			'site_url'    => get_site_url(),
			'identifier' => $identifier_hash,
			'user_id'    => $support_user_id,
			'expiry'     => $expiration_timestamp,
			'is_ssl'     => is_ssl(),
			'timing'     => array(
				'local' => $timing_local,
				'remote' => null,
			),
		);
```
As well as which WP User clicked 'extend'.

Useful for logging on SaaS-side.

**Comment by inztinkt** [comment]
@zackkatz as we're now [sending a timestamp to SaaS on creation](https://github.com/trustedlogin/trustedlogin-ecommerce/issues/277), what data should we be sending to which endpoint on extension?

**Comment by zackkatz** [comment]
@inztinkt Can't we just re-send the same data that we sent before?

I don't know the answer to this question.

**Comment by inztinkt** [comment]
@zackkatz don't think this is completed, so moving back to V1 ahead of call.
