### ISSUE TITLE
Add brute force attack protection

### ISSUE THREAD

**Issue by zackkatz** [trustedlogin/trustedlogin-client#38]
Allow same key many times, but not brute-forcing the accesskey.

Assume user has the endpoint hash and are trying wrong keys.

Allow X bad attempts in X minutes (both should be constants set in the code).

**Comment by inztinkt** [comment]
@zackkatz for the limit and expiry, do we want them to be constants or private variables that can be updated via filters?

**Comment by zackkatz** [comment]
Constants @inztinkt

**Comment by inztinkt** [comment]
✅ got it!

When an attack may be detected, I'm getting ready to ping SaaS via an action hook.

Should I lock down trusted login for a few mins at the same time?
