### ISSUE TITLE
When SaaS triggers 'Reset', handling cached public_key

### ISSUE THREAD

**Issue by inztinkt** [trustedlogin/trustedlogin-client#39]
## Background:
In `TrustedLogin\Encryption()` we add a 'cache' of a Vendor's encryption public_key (fetched from their WP API endpoint) into a namespaced site option (`tl_<ns>_public_key`).

## Problem: 
If the keys are reset on Vendor after an initial TL support agent is created, any future TL envelopes will be encrypted with the wrong public key, and thus won't be possible to decrypt once received.

## Proposed Solution:
We switch from site_option to transient with a 1 hour expiry.
We could also add a url param to the authpage to force a fetch of a new public_key from vendor.

## Alternative Solution:
Don't cache the public key, and always fetch it live from Vendor's site.

Thoughts @zackkatz ?

**Comment by zackkatz** [comment]
Decided on a compromise between the options @inztinkt
