### ISSUE TITLE
Move configuration validation to its own class.

### ISSUE THREAD

**Issue by Shelob9** [trustedlogin/trustedlogin-client#4]
The Client class has _a lot_ of responsibilities. The __constructor method alone is responsible for:

* validating the configuration.
* generating a variety of exceptions
* Generating some WP_Error objects that get passed to a different exception.

I have a few major issues with this:

- It's really hard to reason with this code/ debug it beacuse the validation logic and the other logic like logging, WordPress plugins API, callbacks for admin-ajax, settings API, etc. 
- I'm unclear how to catch these exceptions.

Also line 229 `if ( ! isset( $passed_config['auth']['public_key'] ) ) {` to 264 does not validate a lot of potential errors. That line will generate a warning with the default argument for $config. It does not check if the variable is an array -- the __construct method signature has no type hint. The unit tests not testing what happens when a  stClass object or a JSON _string_ are passed to __construct is  bad smell.

Imagine a Config class like this:

```
namespace TrustedLogin;

class Config
{
	public function __construct(array $config )
	{
		
	}

	public function validate(): Config
	{
		if( '1' == '2'){
			throw new \Exception();
		}
		return $this;
	}
//Getter and setter methods?
}
```

and if the __construct method of Client looked like this:

```php
public function __construct( Config $config ) {
```

Then I could instantiate the client like this:

```php
$config = new Config(['namespace' => 'shawn' ]);
try{
	$config = $config->validate();
	$client = new Client($config);
}catch (\Exception $e ){
	//Don't tell me, a plugin developer
	// how to log errors or show an admin notice using my own special abstraction
	// I will handle this myself.
}
```

**Comment by zackkatz** [comment]
That was my original idea, but for the drop-in file, it would need to be defined above or below the client class. I agree it would be much cleaner!

Same with the button functionality, as you’ll see. 

You still think having multiple classes on same file is preferable?

**Comment by Shelob9** [comment]
> That was my original idea, but for the drop-in file, 
What is "the drop-in file"? 

> You still think having multiple classes on same file is preferable?
No. I do not. I would stick to PSR-4 standard of one class per file.

**Comment by zackkatz** [comment]
I was trying to make it possible to have a single file that developers could include, rather than needing to install via composer. That's why the Client class is such a All-in-One beast.

But you're right: it really would be better to be properly-constructed library.

**Comment by Shelob9** [comment]
I feel like this is developing to the assumption that WordPress plugin
developers are all terrible PHP developers. I don't think that's an
accurate or fair assumption.

Even if it were how does having one file, versus a folder of files help the
poor developer who knows not of autoloaders and reading documentation?

I'd rather make it easy for someone to do it the right way and document
work arounds.
