### ISSUE TITLE
Decouple admin-ajax callbacks from business logic.

### ISSUE THREAD

**Issue by Shelob9** [trustedlogin/trustedlogin-client#5]
A WordPress plugin using core's admin-ajax API is a common practice, but it's a really bad smell for a product that is security focused to repropose it for plugin settings. It's also not performant. It's also the endpoint that gets attacked the most.

If you want to have this as the insecure default fine, I get it WordPress. But please refactor so that the callbacks for admin-ajax are only responsible for validating/ authorizing the request and then dispatching to a class that was responsible only for handling the actual business logic of the request. 

For example in the god class there is "ajax_generate_support" method, from line 489 on is the business logic

https://github.com/trustedlogin/trustedlogin-client/blob/develop/src/Client.php#L489-L526

If that was in its own class, with the single responsibility of generating a support user, then I -- as a plugin developer -- could hook that up to the REST API with my own standard abstraction, endpoint naming, and avoid the performance and security concerns of admin-ajax.

**Comment by zackkatz** [comment]
I was going to refactor that into its own method…would that be an okay middle-ground?

**Comment by Shelob9** [comment]
> I was going to refactor that into its own method…would that be an okay middle-ground?

No. I'd keep it as-is if adding additional classes is a problem. It's going to be even harder to reason what methods go with what concerns, and I don't see how that would solve the problem. It will make future refactoring harder.

Why is adding another class a problem?
