### ISSUE TITLE
Asset registration 

### ISSUE THREAD

**Issue by Shelob9** [trustedlogin/trustedlogin-client#6]
Things I see as issues:

- No way to remove this hook `add_action( 'admin_enqueue_scripts', array( $this, 'register_assets' ) );`
- Assets handles are not vendor prefixed -- for the client plugin. How can I unregistered `jquery-confirm` or `trusted-login` registered by plugin A, but not the copy registered by plugin B?
- What if I want to use my own CSS that matches my plugin's branding? 
- What if jQuery confirm has a conflict in my admin.

So I think at a minimum namespacing these handles is necessary and adding filters or something to prevent any of the `wp_register_script` or `wp_enqueue_script` calls from running. Ideally, this responsibility would be removed from the `Client` class and I as a plugin developer could easily remove the default hooks that the client adds and use my own system.

**Comment by zackkatz** [comment]
There's now a `registers_assets` setting in the Config object that disables asset registration. The assets are also all namespaced.
