### ISSUE TITLE
Potential stored XSS vuldrabilities in `Client::generate_button()`

### ISSUE THREAD

**Issue by Shelob9** [trustedlogin/trustedlogin-client#7]
Data is printed to the DOM without escape functions: 

https://github.com/trustedlogin/trustedlogin-client/blob/987efd9a362a3294e921e9f64ae0f796cbc84158/src/Client.php#L608-L615

See: https://wpvip.com/documentation/vip-go/validating-sanitizing-and-escaping/#always-escape-late

**Comment by Shelob9** [comment]
Similar issues:

- https://github.com/trustedlogin/trustedlogin-client/blob/987efd9a362a3294e921e9f64ae0f796cbc84158/src/Client.php#L422-L430
- https://github.com/trustedlogin/trustedlogin-client/blob/987efd9a362a3294e921e9f64ae0f796cbc84158/src/Client.php#L657

**Comment by zackkatz** [comment]
`support_url` is escaped later as well.

The array printed to JS object is converted to JSON by `wp_localize_script()`. So are the `$return_data` (sent as JSON).

I don't think this is an issue. See https://github.com/WordPress/WordPress-Coding-Standards/issues/1270#issue-285069432
