### ISSUE TITLE
Use lib_sodium for encryption

### ISSUE THREAD

**Issue by Shelob9** [trustedlogin/trustedlogin-client#8]
It [is better to rely on PHP's encryption system](https://twitter.com/EricMann/status/1226890476030062595)  than to create something custom with `openssl_*` functions.

https://github.com/trustedlogin/trustedlogin-client/blob/987efd9a362a3294e921e9f64ae0f796cbc84158/src/Client.php#L2498

This library is included in PHP so it runs faster and [there is a polyfill](https://github.com/paragonie/sodium_compat) for out of date versions of PHP.

I would STRONGLY recommend using a secure encryption system like this one: https://gist.github.com/ericmann/1e54625d81a35b243eec0d67ae7b868f

**Comment by zackkatz** [comment]
Nice, thanks for pointing out https://github.com/paragonie/sodium_compat — that’s a great option.
